import type { Metadata } from "next";
import { Literata } from "next/font/google";
import "./globals.css";

import { ReactLenis } from "@/utils/lenis";

import Navigation from "@/components/navigation";

const literata = Literata({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className={`${literata.className} antialiased`}>
          <Navigation />
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
