import type { Metadata } from "next";
import { Literata } from "next/font/google";
import "./globals.css";

import { ReactLenis } from "@/utils/lenis";

const literata = Literata({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className={`${literata.className} antialiased`}>{children}</body>
      </ReactLenis>
    </html>
  );
}
